Web_AcuerdosComerciales/LV_Template_MVC4/Controllers/AcuerdosController.cs
using LV_Template_MVC4.Interfaces;
using LV_Template_MVC4.Models;
using LV_Template_MVC4.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LV_Template_MVC4.Controllers
{
   
    public class AcuerdosController : Controller
    {

        private readonly IActivosLVServices activosLVServices;
        private readonly IAcuerdosServices acuerdosServices;

        public AcuerdosController()
        {
            activosLVServices = new ActivosLVServices();
            acuerdosServices = new AcuerdosServices();
        }
        //
        // GET: /Acuerdos/

        public ActionResult Index()
        {
            var acuerdos = activosLVServices.Get(2);
            var acuerdoView = new ActivosViewModel()
            {
                AcivoList = acuerdos.ToList(),
                Activo = new Activos(),
                Acuerdo = new Acuerdo()

            };
            return View(acuerdoView);
        }

        [HttpPost]
        public ActionResult Index(ActivosViewModel activoView)
        {
            int idFilter = (int)activoView.SelectFilter;
            var acuerdos = activosLVServices.Get(idFilter);

            activoView.AcivoList = acuerdos.ToList();

            return View("Index", activoView);
        }

        [HttpPost]
        public ActionResult RelacionarView(ActivosViewModel activo)
        {
            // se obtiene el listado seleccionado
            // este listado puede tener o no un acuerdo asignado
            var selectedItem = activo.AcuerdosSelected.Split(',');

            var fondos = activosLVServices.GetByCodes(selectedItem);
            if (!fondos.Any())
            {
                // not found view
                return View("Page404");
            }
            activo.AcivoList = fondos.ToList();
            //si el listado seleccionado presenta valores iguales, dichos valores se establecen como valores por defecto 
            var fondosAsociados = fondos.Where(f => f.IdAcuerdo != null);
            var codigoInterno = fondosAsociados.Select(f => f.CodigoInterno).Distinct().Count() == 1 ? fondos.FirstOrDefault().CodigoInterno : "";
            var fecha = fondosAsociados.Select(f => f.FechaVigenciaDesde).Distinct().Count() == 1 ? fondos.FirstOrDefault().FechaVigenciaDesde : "";
            var tipoPago = fondosAsociados.Select(f => f.TipoPago).Distinct().Count() == 1 ? fondos.FirstOrDefault().TipoPago : "";
            var tipoRebate = fondosAsociados.Select(f => f.TipoRebate).Distinct().Count() == 1 ? fondos.FirstOrDefault().TipoRebate : "";
            var rebate = fondosAsociados.Select(f => f.RebateAnual).Distinct().Count() == 1 ? fondos.FirstOrDefault().RebateAnual : null;
            var manager = fondosAsociados.Select(f => f.IdManager).Distinct().Count() == 1 ? fondos.FirstOrDefault().IdManager : null;
            var managerFree = fondosAsociados.Select(f => f.ManagementFree).Distinct().Count() == 1 ? fondos.FirstOrDefault().ManagementFree : null;
            var acuerdo = fondosAsociados.Select(f => f.AcuerdoComercial).Distinct().Count() == 1 ? fondos.FirstOrDefault().AcuerdoComercial : null;
            DateTime fechaVig;
            activo.Acuerdo = new Acuerdo()
            {
                CodigoInterno = codigoInterno,
                TipoPago = tipoPago,
                TipoRebate = tipoRebate,
                RebateAnual = rebate,
                IdManager = manager ?? 0,
                ManagementFree = managerFree,
                AcuerdoComercial = acuerdo,
                FechaVigenciaDesde = DateTime.TryParse(fecha, out fechaVig) ? fechaVig : (DateTime?)null

            };



            return View(activo);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Relacionar(ActivosViewModel activoView)
        {
            // validaciones de todos los parametros
            if (!ModelState.IsValid)
            {
                List<string> errores = new List<string>();
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        errores.Add(error.ErrorMessage);
                    }
                }

                return Json(new { data = "NOK", errormesages = errores.ToArray() });
            }


            try
            {
                Acuerdo acuerdo = activoView.Acuerdo;
                if (acuerdo.TipoRebate == "V" && acuerdo.ManagementFree.HasValue && acuerdo.AcuerdoComercial.HasValue)
                {
                    acuerdo.RebateAnual = acuerdo.ManagementFree * acuerdo.AcuerdoComercial;
                }
                // cada uno de los activos seleccionados se transforma en un acuerdo comercial
                AcuerdoList acuerdos = new AcuerdoList();
                acuerdos.Acuerdos = activoView.AcivoList.Select(a => new Acuerdo()
                {
                    CODIGO_PRODUCTO = a.CODIGO_PRODUCTO,
                    AcuerdoComercial = acuerdo.AcuerdoComercial,
                    CodigoInterno = acuerdo.CodigoInterno,
                    FechaVigenciaDesde = acuerdo.FechaVigenciaDesde,
                    IdManager = acuerdo.IdManager,
                    ManagementFree = acuerdo.ManagementFree,
                    NemoBaseComercial = acuerdo.CodigoInterno,
                    RebateAnual = acuerdo.RebateAnual,
                    TipoPago = acuerdo.TipoPago,
                    TipoRebate = acuerdo.TipoRebate,
                    UsuarioReg = User.Identity.Name,

                });

                acuerdosServices.Relacionar(acuerdos);
                return Json(new { data = "OK" });

            }
            catch (Exception ex)
            {
                return Json(new { data = "NOK", errormesages = new List<string> { ex.Message }.ToArray() });
            }
        }


        public ActionResult Edit(int id)
        {
            var acuerdo = acuerdosServices.GetById(id);
            if (null == acuerdo)
            {
                // not found view
                return View("Page404");
            }
            IEnumerable<Acuerdo> acuerdosHistoricos = acuerdosServices.GetHistoricos(acuerdo.CODIGO_PRODUCTO);

            AcuerdoViewModel view = new AcuerdoViewModel()
            {
                Acuerdo = acuerdo,
                Acuerdos = acuerdosHistoricos
            };
            return View(view);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(Acuerdo acuerdo)
        {
            acuerdo.UsuarioReg = User.Identity.Name;
            // validaciones de todos los parametros
            if (!ModelState.IsValid)
            {
                List<string> errores = new List<string>();
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        errores.Add(error.ErrorMessage);
                    }
                }

                return Json(new { data = "NOK", errormesages = errores.ToArray() });
            }

            if (acuerdo.TipoRebate == "V" && acuerdo.ManagementFree.HasValue && acuerdo.AcuerdoComercial.HasValue)
            {
                acuerdo.RebateAnual = acuerdo.ManagementFree * acuerdo.AcuerdoComercial;
            }

            try
            {
                acuerdosServices.Edit(acuerdo);
                return Json(new { data = "OK" });

            }
            catch (Exception ex)
            {
                return Json(new { data = "NOK", errormesages = new List<string> { ex.Message }.ToArray() });
            }

        }

    }
}

Web_AcuerdosComerciales/LV_Template_MVC4/Controllers/ManagersController.cs
using LV_Template_MVC4.Interfaces;
using LV_Template_MVC4.Models;
using LV_Template_MVC4.Services;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace LV_Template_MVC4.Controllers
{

    public class ManagersController : Controller
    {
        private readonly IManagerServices managerServices;
        public ManagersController()
        {
            managerServices = new ManagerServices();
        }


        /// <summary>
        /// Obtiene el listado de managers
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var managers = managerServices.Get();

            ManagerViewModel viewModel = new ManagerViewModel()
            {
                Manager = new Manager(),
                ManagerList = managers

            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(Manager manager)
        {

            // validaciones de todos los parametros
            if (!ModelState.IsValid)
            {
                List<string> errores = new List<string>();
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        errores.Add(error.ErrorMessage);
                    }
                }

                return Json(new { data = "NOK", errormesages = errores.ToArray() });
            }

            try
            {
                managerServices.Add(manager);
                return Json(new { data = "OK" });

            }
            catch (Exception ex)
            {
                return Json(new { data = "NOK", errormesages = new List<string> { ex.Message }.ToArray() });
            }
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            List<string> errores = new List<string>();
            try
            {
                managerServices.Delete(id);
                return Json(new { data = "OK" });
            }
            catch (Exception ex)
            {
                errores.Add(ex.Message);
                return Json(new { data = "NOK", errormesages = errores.ToArray() });
            }

        }


        public ActionResult Edit(int id)
        {
            var managers = managerServices.GetById(id);

            if (null == managers)
            {
                // not found view
                return View("Page404");
            }

            return View(managers);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(Manager manager)
        {

            // validaciones de todos los parametros
            if (!ModelState.IsValid)
            {
                List<string> errores = new List<string>();
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        errores.Add(error.ErrorMessage);
                    }
                }

                return Json(new { data = "NOK", errormesages = errores.ToArray() });
            }

            try
            {
                managerServices.Update(manager);
                return Json(new { data = "OK" });

            }
            catch (Exception ex)
            {
                return Json(new { data = "NOK", errormesages = new List<string> { ex.Message }.ToArray() });
            }
        }

    }
}

Web_AcuerdosComerciales/LV_Template_MVC4/Controllers/ReporteController.cs
using LV_Template_MVC4.Interfaces;
using LV_Template_MVC4.Models;
using LV_Template_MVC4.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LV_Template_MVC4.Controllers
{
   
    public class ReporteController : Controller
    {
        private readonly IReportServices reportServices;
        public ReporteController()
        {
            reportServices = new ReportServices();
        }

        public ActionResult Diario()
        {
            ReporteViewModel view = new ReporteViewModel() {
                ReporteDiarioList = new List<ReporteDiario>()
            };

            return View(view);
        }

        [HttpPost]
        public ActionResult Diario(ReporteViewModel view)
        {
            view.ReporteDiarioList = reportServices.GetDiario(view.PeriodoSeleccionado.ToString(), view.IdManager, view.Fondo);

            return View("Diario", view);
        }
        public ActionResult Resumen()
        {
            ReporteViewModel view = new ReporteViewModel()
            {
               ReporteResumenList = new List<ReporteResumen>()
            };

            return View(view);
        }

        [HttpPost]
        public ActionResult Resumen(ReporteViewModel view)
        {
            view.ReporteResumenList = reportServices.GetResumen(view.PeriodoSeleccionado.ToString());

            return View("Resumen", view);
        }



    }
}

Web_AcuerdosComerciales/LV_Template_MVC4/Views/Shared/Page404.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- 404 Error Text -->
    <div class="text-center">
        <div class="error mx-auto" data-text="404">404</div>
        <p class="lead text-gray-800 mb-5">Page Not Found</p>
        <p class="text-gray-500 mb-0">It looks like you found a glitch in the matrix...</p>
        @Html.ActionLink("Back to Dashboard", "Index","Managers")
    </div>
</div>

Web_AcuerdosComerciales/LV_Template_MVC4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LarrainVial - @ViewBag.Title</title>

    <link rel="icon" href="@Url.Content("~/favicon.ico")" type="image/x-icon" />
    <link rel="shortcut icon" href="@Url.Content("~/favicon.ico")" type="image/x-icon" />


    <link href="@Url.Content("~/Content/adminlte.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/select2-bootstrap4.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/fontawesome-free/css/all.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/icheck-bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/OverlayScrollbars.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/daterangepicker.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/summernote-bs4.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/select2.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/dataTables.bootstrap4.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/buttons.dataTables.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/rowGroup.dataTables.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/iziToast.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/animate.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/select.dataTables.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/iziModal.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/icheck-bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/loader.css")" rel="stylesheet">



    @*@Styles.Render("~/Content/css")*@
</head>



<body class="hold-transition sidebar-mini layout-fixed">

    <div id="loader-wrapper">
        <div id="most">
            <img src="@Url.Content("~/Content/img/logo_larrainvial_gris.png")" alt="LarrainVial" width="250" />
        </div>
        <div id="loader"></div>
        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>
    </div>

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
        </ul>
        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                    <span class="mr-2 text-sm">@User.Identity.Name</span>
                    <i class="fas fa-user-circle"></i>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <div class="content-wrapper">
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a class="brand-link logo-switch" href="@Url.Action("Index", "Home")">
                <img src="@Url.Content("~/Content/img/cuadrado.png")" class="brand-image-xl logo-xs" style="width:25px; height:auto; margin:10px 5px;" />
                <img src="@Url.Content("~/Content/img/logo_larrainvial_blanco.png")" class="brand-image-xs logo-xl" style="width:155px; height:auto; margin: 1px 25px;">
            </a>
            <!-- Sidebar -->
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-cogs"></i>
                                <p>
                                    Mantenedores
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">

                                <li class="nav-item">
                                    <a id="managers" href="@Url.Action("Index", "Managers")" class="nav-link">
                                        <i class="far fa-circle nav-icon fx-xs"></i>
                                        <p class="text-sm">Managers</p>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a id="acuerdos" href="@Url.Action("Index", "Acuerdos")" class="nav-link">
                                        <i class="far fa-circle nav-icon fx-xs"></i>
                                        <p class="text-sm">Acuerdos Comerciales</p>
                                    </a>
                                </li>

                            </ul>
                        </li>

                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-server"></i>
                                <p>
                                    Reportes
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">

                                <li class="nav-item">
                                    <a id="clientesSupervisor" href="@Url.Action("Diario", "Reporte")" class="nav-link">
                                        <i class="far fa-circle nav-icon fx-xs"></i>
                                        <p class="text-sm">Reporte diario </p>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a id="clientesSupervisorAgente" href="@Url.Action("Resumen", "Reporte")" class="nav-link">
                                        <i class="far fa-circle nav-icon fx-xs"></i>
                                        <p class="text-sm">Resumen </p>
                                    </a>
                                </li>

                            </ul>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
            <!-- /.sidebar -->
        </aside>
        @RenderBody()
    </div>

    <footer class="main-footer">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>
                    LarrainVial Chile. Avenida El Bosque Norte 0177, piso 1, Las Condes. Santiago, Chile. &copy;
                    Copyright @DateTime.Now.Year - Todos los Derechos Reservados.
                </span>
            </div>
        </div>
    </footer>


    <script src="@Url.Content("~/Scripts/jquery-3.4.1.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.js")"></script>
    <script src="@Url.Content("~/Scripts/character-counter.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.bundle.js")"></script>
    <script src="@Url.Content("~/Scripts/adminlte.js")"></script>
    <script src="@Url.Content("~/Scripts/moment.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.knob.min.js")"></script>
    <script src="@Url.Content("~/Scripts/summernote-bs4.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.overlayScrollbars.js")"></script>
    <script src="@Url.Content("~/Scripts/select2.full.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/Scripts/dataTables.buttons.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jszip.min.js")"></script>
    <script src="@Url.Content("~/Scripts/buttons.html5.min.js")"></script>
    <script src="@Url.Content("~/Scripts/dataTables.rowGroup.min.js")"></script>
    <script src="@Url.Content("~/Scripts/dataTables.bootstrap4.js")"></script>
    <script src="@Url.Content("~/Scripts/iziToast.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.rut.chileno.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.datetimepicker.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.blockUI.js")"></script>
    <script src="@Url.Content("~/Scripts/dataTables.select.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/Scripts/iziModal.js")"></script>
    <script src="@Url.Content("~/Scripts/customs.js")"></script>
    <script src="@Url.Content("~/Scripts/date-eu.js")"></script>


    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/modernizr")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@

    @RenderSection("scripts", required: false)



    <script>

        function desbloquear() {
            $("#loader-wrapper").delay(250).fadeOut(1000);
        }
        function bloquear() {
            $('#loader-wrapper').css({ display: 'block' });
        }

        $(document).ready(function () {

            desbloquear();

            var url = window.location;

            $('ul.nav-sidebar a').filter(function () {
                return this.href == url;
            }).addClass('active');

            $('ul.nav-treeview a').filter(function () {
                return this.href == url;
            }).parentsUntil(".nav-sidebar > .nav-treeview").addClass('menu-open').prev('a').addClass('active');


        });

    </script>


</body>

</html>